export default function Page() {
  return (
    <div className="bg-gray-800">
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
      <div>Dahs</div>
    </div>
  );
}
